### ISSUE TITLE
thread 'main' panicked

### ISSUE THREAD

**Issue by Matyu9** [Asthowen/AFetch#2]
**Describe the bug**
It's just doesn't work :/

**To Reproduce**
1. Run 'cargo build --release'
2. Go to 'target/release/'
3. Run 'afetch'

**Expected behavior**

**Screenshots**
![image](https://github.com/Asthowen/AFetch/assets/59774749/dd8767f2-3f7a-4bb8-bdb9-e81e2da7011d)

**Device infos (please complete the following information):**
 - OS: Fedora 38 (Workstation Edition) 
 - Terminal name: Terminal
 - Terminal version: V3.48.1
 - AFetch Version: I built it directly from the repo

**Comment by Asthowen** [comment]
Fixed in [0.0.4](https://github.com/Asthowen/AFetch/releases/tag/0.0.4).
